import httpx

CRYPTOFEED_WERKS = "cryptofeed-werks"

GOOGLE_APPLICATION_CREDENTIALS = "GOOGLE_APPLICATION_CREDENTIALS"
PROJECT_ID = "PROJECT_ID"
BIGQUERY_LOCATION = "BIGQUERY_LOCATION"
BIGQUERY_DATASET = "BIGQUERY_DATASET"
BIGQUERY_TABLES = "BIGQUERY_TABLES"
SERVICE_ACCOUNT = "SERVICE_ACCOUNT"
SENTRY_DSN = "SENTRY_DSN"


PRODUCTION_ENV_VARS = (
    PROJECT_ID,
    BIGQUERY_LOCATION,
    BIGQUERY_DATASET,
    SENTRY_DSN,
)


HTTPX_ERRORS = (
    httpx.ConnectError,
    httpx.ConnectTimeout,
    httpx.ReadError,
    httpx.ReadTimeout,
)
