CRYPTOBLOTTER = "cryptoblotter"

GOOGLE_APPLICATION_CREDENTIALS = "GOOGLE_APPLICATION_CREDENTIALS"
FIREBASE_ADMIN_CREDENTIALS = "FIREBASE_ADMIN_CREDENTIALS"
PROJECT_ID = "PROJECT_ID"
SERVICE_ACCOUNT = "SERVICE_ACCOUNT"
SENTRY_DSN = "SENTRY_DSN"

GCP_APPLICATION_CREDENTIALS = (
    GOOGLE_APPLICATION_CREDENTIALS,
    FIREBASE_ADMIN_CREDENTIALS,
)

LOCAL_ENV_VARS = (
    GOOGLE_APPLICATION_CREDENTIALS,
    FIREBASE_ADMIN_CREDENTIALS,
    PROJECT_ID,
    SERVICE_ACCOUNT,
    SENTRY_DSN,
)

PRODUCTION_ENV_VARS = (PROJECT_ID, SENTRY_DSN)
