CRYPTOBLOTTER = "cryptoblotter"

GOOGLE_APPLICATION_CREDENTIALS = "GOOGLE_APPLICATION_CREDENTIALS"
FIREBASE_ADMIN_CREDENTIALS = "FIREBASE_ADMIN_CREDENTIALS"
PROJECT_ID = "PROJECT_ID"

GCP_APPLICATION_CREDENTIALS = (
    GOOGLE_APPLICATION_CREDENTIALS,
    FIREBASE_ADMIN_CREDENTIALS,
)

PRODUCTION_ENV_VARS = (PROJECT_ID,)
